/* 
 * assembly.education
 *
 * Developer API for assembly.education.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: help@assembly.education
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = AssemblyClient.Client.SwaggerDateConverter;

namespace AssemblyClient.Model
{
    /// <summary>
    /// The assessment is the grouping that knits together a range of concepts. The name of the assessment also refers to the source of the result (for example, a Key Stage national assessment, or a standardised assessment provider).
    /// </summary>
    [DataContract]
    public partial class AssessmentListData :  IEquatable<AssessmentListData>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AssessmentListData" /> class.
        /// </summary>
        /// <param name="_object">Object type.</param>
        /// <param name="id">Internal stable ID given to all assessments on the Platform.</param>
        /// <param name="name">The name of the assessment.</param>
        /// <param name="familyId">Internal stable ID given to all assessment families on the Platform.</param>
        /// <param name="familyName">The name of the assessment family.</param>
        /// <param name="misMappings">Names of any MIS assessments (e.g. SIMS Aspects) that have been mapped to the assessment.</param>
        public AssessmentListData(string _object = default(string), int? id = default(int?), string name = default(string), int? familyId = default(int?), string familyName = default(string), List<string> misMappings = default(List<string>))
        {
            this._object = _object;
            this.id = id;
            this.name = name;
            this.family_id = familyId;
            this.family_name = familyName;
            this.mis_mappings = misMappings;
        }
        
        /// <summary>
        /// Object type
        /// </summary>
        /// <value>Object type</value>
        [DataMember(Name="object", EmitDefaultValue=false)]
        public string _object { get; set; }

        /// <summary>
        /// Internal stable ID given to all assessments on the Platform
        /// </summary>
        /// <value>Internal stable ID given to all assessments on the Platform</value>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public int? id { get; set; }

        /// <summary>
        /// The name of the assessment
        /// </summary>
        /// <value>The name of the assessment</value>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string name { get; set; }

        /// <summary>
        /// Internal stable ID given to all assessment families on the Platform
        /// </summary>
        /// <value>Internal stable ID given to all assessment families on the Platform</value>
        [DataMember(Name="family_id", EmitDefaultValue=false)]
        public int? family_id { get; set; }

        /// <summary>
        /// The name of the assessment family
        /// </summary>
        /// <value>The name of the assessment family</value>
        [DataMember(Name="family_name", EmitDefaultValue=false)]
        public string family_name { get; set; }

        /// <summary>
        /// Names of any MIS assessments (e.g. SIMS Aspects) that have been mapped to the assessment
        /// </summary>
        /// <value>Names of any MIS assessments (e.g. SIMS Aspects) that have been mapped to the assessment</value>
        [DataMember(Name="mis_mappings", EmitDefaultValue=false)]
        public List<string> mis_mappings { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AssessmentListData {\n");
            sb.Append("  _object: ").Append(_object).Append("\n");
            sb.Append("  id: ").Append(id).Append("\n");
            sb.Append("  name: ").Append(name).Append("\n");
            sb.Append("  family_id: ").Append(family_id).Append("\n");
            sb.Append("  family_name: ").Append(family_name).Append("\n");
            sb.Append("  mis_mappings: ").Append(mis_mappings).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AssessmentListData);
        }

        /// <summary>
        /// Returns true if AssessmentListData instances are equal
        /// </summary>
        /// <param name="input">Instance of AssessmentListData to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AssessmentListData input)
        {
            if (input == null)
                return false;

            return 
                (
                    this._object == input._object ||
                    (this._object != null &&
                    this._object.Equals(input._object))
                ) && 
                (
                    this.id == input.id ||
                    (this.id != null &&
                    this.id.Equals(input.id))
                ) && 
                (
                    this.name == input.name ||
                    (this.name != null &&
                    this.name.Equals(input.name))
                ) && 
                (
                    this.family_id == input.family_id ||
                    (this.family_id != null &&
                    this.family_id.Equals(input.family_id))
                ) && 
                (
                    this.family_name == input.family_name ||
                    (this.family_name != null &&
                    this.family_name.Equals(input.family_name))
                ) && 
                (
                    this.mis_mappings == input.mis_mappings ||
                    this.mis_mappings != null &&
                    this.mis_mappings.SequenceEqual(input.mis_mappings)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this._object != null)
                    hashCode = hashCode * 59 + this._object.GetHashCode();
                if (this.id != null)
                    hashCode = hashCode * 59 + this.id.GetHashCode();
                if (this.name != null)
                    hashCode = hashCode * 59 + this.name.GetHashCode();
                if (this.family_id != null)
                    hashCode = hashCode * 59 + this.family_id.GetHashCode();
                if (this.family_name != null)
                    hashCode = hashCode * 59 + this.family_name.GetHashCode();
                if (this.mis_mappings != null)
                    hashCode = hashCode * 59 + this.mis_mappings.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
