/* 
 * assembly.education
 *
 * Developer API for assembly.education.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: help@assembly.education
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using assembly-client-dotnet.Api;
using assembly-client-dotnet.Model;
using assembly-client-dotnet.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace assembly-client-dotnet.Test
{
    /// <summary>
    ///  Class for testing AssessmentPoint
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AssessmentPointTests
    {
        // TODO uncomment below to declare an instance variable for AssessmentPoint
        //private AssessmentPoint instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AssessmentPoint
            //instance = new AssessmentPoint();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AssessmentPoint
        /// </summary>
        [Test]
        public void AssessmentPointInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AssessmentPoint
            //Assert.IsInstanceOfType<AssessmentPoint> (instance, "variable 'instance' is a AssessmentPoint");
        }


        /// <summary>
        /// Test the property 'Object'
        /// </summary>
        [Test]
        public void ObjectTest()
        {
            // TODO unit test for the property 'Object'
        }
        /// <summary>
        /// Test the property 'Rank'
        /// </summary>
        [Test]
        public void RankTest()
        {
            // TODO unit test for the property 'Rank'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'YearCode'
        /// </summary>
        [Test]
        public void YearCodeTest()
        {
            // TODO unit test for the property 'YearCode'
        }

    }

}
