/* 
 * assembly.education
 *
 * Developer API for assembly.education.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: help@assembly.education
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using assembly-client-dotnet.Api;
using assembly-client-dotnet.Model;
using assembly-client-dotnet.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace assembly-client-dotnet.Test
{
    /// <summary>
    ///  Class for testing CreateResultPayload
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CreateResultPayloadTests
    {
        // TODO uncomment below to declare an instance variable for CreateResultPayload
        //private CreateResultPayload instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CreateResultPayload
            //instance = new CreateResultPayload();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CreateResultPayload
        /// </summary>
        [Test]
        public void CreateResultPayloadInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CreateResultPayload
            //Assert.IsInstanceOfType<CreateResultPayload> (instance, "variable 'instance' is a CreateResultPayload");
        }


        /// <summary>
        /// Test the property 'SubjectId'
        /// </summary>
        [Test]
        public void SubjectIdTest()
        {
            // TODO unit test for the property 'SubjectId'
        }
        /// <summary>
        /// Test the property 'FacetId'
        /// </summary>
        [Test]
        public void FacetIdTest()
        {
            // TODO unit test for the property 'FacetId'
        }
        /// <summary>
        /// Test the property 'AssessmentPointRank'
        /// </summary>
        [Test]
        public void AssessmentPointRankTest()
        {
            // TODO unit test for the property 'AssessmentPointRank'
        }
        /// <summary>
        /// Test the property 'AssessmentId'
        /// </summary>
        [Test]
        public void AssessmentIdTest()
        {
            // TODO unit test for the property 'AssessmentId'
        }
        /// <summary>
        /// Test the property 'Results'
        /// </summary>
        [Test]
        public void ResultsTest()
        {
            // TODO unit test for the property 'Results'
        }

    }

}
