/* 
 * assembly.education
 *
 * Developer API for assembly.education.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: help@assembly.education
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using assembly-client-dotnet.Api;
using assembly-client-dotnet.Model;
using assembly-client-dotnet.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace assembly-client-dotnet.Test
{
    /// <summary>
    ///  Class for testing RegistrationGroup
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RegistrationGroupTests
    {
        // TODO uncomment below to declare an instance variable for RegistrationGroup
        //private RegistrationGroup instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RegistrationGroup
            //instance = new RegistrationGroup();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RegistrationGroup
        /// </summary>
        [Test]
        public void RegistrationGroupInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" RegistrationGroup
            //Assert.IsInstanceOfType<RegistrationGroup> (instance, "variable 'instance' is a RegistrationGroup");
        }


        /// <summary>
        /// Test the property 'Object'
        /// </summary>
        [Test]
        public void ObjectTest()
        {
            // TODO unit test for the property 'Object'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'SupervisorIds'
        /// </summary>
        [Test]
        public void SupervisorIdsTest()
        {
            // TODO unit test for the property 'SupervisorIds'
        }
        /// <summary>
        /// Test the property 'StudentIds'
        /// </summary>
        [Test]
        public void StudentIdsTest()
        {
            // TODO unit test for the property 'StudentIds'
        }

    }

}
