/* 
 * assembly.education
 *
 * Developer API for assembly.education.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: help@assembly.education
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using assembly-client-dotnet.Api;
using assembly-client-dotnet.Model;
using assembly-client-dotnet.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace assembly-client-dotnet.Test
{
    /// <summary>
    ///  Class for testing SchoolDetailsListData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SchoolDetailsListDataTests
    {
        // TODO uncomment below to declare an instance variable for SchoolDetailsListData
        //private SchoolDetailsListData instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SchoolDetailsListData
            //instance = new SchoolDetailsListData();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SchoolDetailsListData
        /// </summary>
        [Test]
        public void SchoolDetailsListDataInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SchoolDetailsListData
            //Assert.IsInstanceOfType<SchoolDetailsListData> (instance, "variable 'instance' is a SchoolDetailsListData");
        }


        /// <summary>
        /// Test the property 'Object'
        /// </summary>
        [Test]
        public void ObjectTest()
        {
            // TODO unit test for the property 'Object'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Urn'
        /// </summary>
        [Test]
        public void UrnTest()
        {
            // TODO unit test for the property 'Urn'
        }
        /// <summary>
        /// Test the property 'LaCode'
        /// </summary>
        [Test]
        public void LaCodeTest()
        {
            // TODO unit test for the property 'LaCode'
        }
        /// <summary>
        /// Test the property 'LaName'
        /// </summary>
        [Test]
        public void LaNameTest()
        {
            // TODO unit test for the property 'LaName'
        }
        /// <summary>
        /// Test the property 'EstablishmentNumber'
        /// </summary>
        [Test]
        public void EstablishmentNumberTest()
        {
            // TODO unit test for the property 'EstablishmentNumber'
        }
        /// <summary>
        /// Test the property 'EstablishmentType'
        /// </summary>
        [Test]
        public void EstablishmentTypeTest()
        {
            // TODO unit test for the property 'EstablishmentType'
        }
        /// <summary>
        /// Test the property 'Phase'
        /// </summary>
        [Test]
        public void PhaseTest()
        {
            // TODO unit test for the property 'Phase'
        }
        /// <summary>
        /// Test the property 'Street'
        /// </summary>
        [Test]
        public void StreetTest()
        {
            // TODO unit test for the property 'Street'
        }
        /// <summary>
        /// Test the property 'Town'
        /// </summary>
        [Test]
        public void TownTest()
        {
            // TODO unit test for the property 'Town'
        }
        /// <summary>
        /// Test the property 'Postcode'
        /// </summary>
        [Test]
        public void PostcodeTest()
        {
            // TODO unit test for the property 'Postcode'
        }
        /// <summary>
        /// Test the property 'HeadTeacher'
        /// </summary>
        [Test]
        public void HeadTeacherTest()
        {
            // TODO unit test for the property 'HeadTeacher'
        }

    }

}
