/* 
 * assembly.education
 *
 * Developer API for assembly.education.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: help@assembly.education
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using assembly-client-dotnet.Api;
using assembly-client-dotnet.Model;
using assembly-client-dotnet.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace assembly-client-dotnet.Test
{
    /// <summary>
    ///  Class for testing StaffContractListData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class StaffContractListDataTests
    {
        // TODO uncomment below to declare an instance variable for StaffContractListData
        //private StaffContractListData instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of StaffContractListData
            //instance = new StaffContractListData();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of StaffContractListData
        /// </summary>
        [Test]
        public void StaffContractListDataInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" StaffContractListData
            //Assert.IsInstanceOfType<StaffContractListData> (instance, "variable 'instance' is a StaffContractListData");
        }


        /// <summary>
        /// Test the property 'Object'
        /// </summary>
        [Test]
        public void ObjectTest()
        {
            // TODO unit test for the property 'Object'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'StaffMemberId'
        /// </summary>
        [Test]
        public void StaffMemberIdTest()
        {
            // TODO unit test for the property 'StaffMemberId'
        }
        /// <summary>
        /// Test the property 'StartDate'
        /// </summary>
        [Test]
        public void StartDateTest()
        {
            // TODO unit test for the property 'StartDate'
        }
        /// <summary>
        /// Test the property 'EndDate'
        /// </summary>
        [Test]
        public void EndDateTest()
        {
            // TODO unit test for the property 'EndDate'
        }
        /// <summary>
        /// Test the property 'NationalInsuranceNumber'
        /// </summary>
        [Test]
        public void NationalInsuranceNumberTest()
        {
            // TODO unit test for the property 'NationalInsuranceNumber'
        }
        /// <summary>
        /// Test the property 'PayrollNumber'
        /// </summary>
        [Test]
        public void PayrollNumberTest()
        {
            // TODO unit test for the property 'PayrollNumber'
        }
        /// <summary>
        /// Test the property 'ContractType'
        /// </summary>
        [Test]
        public void ContractTypeTest()
        {
            // TODO unit test for the property 'ContractType'
        }
        /// <summary>
        /// Test the property 'Post'
        /// </summary>
        [Test]
        public void PostTest()
        {
            // TODO unit test for the property 'Post'
        }
        /// <summary>
        /// Test the property 'Origin'
        /// </summary>
        [Test]
        public void OriginTest()
        {
            // TODO unit test for the property 'Origin'
        }
        /// <summary>
        /// Test the property 'Destination'
        /// </summary>
        [Test]
        public void DestinationTest()
        {
            // TODO unit test for the property 'Destination'
        }
        /// <summary>
        /// Test the property 'DailyRate'
        /// </summary>
        [Test]
        public void DailyRateTest()
        {
            // TODO unit test for the property 'DailyRate'
        }
        /// <summary>
        /// Test the property 'PayReviewDate'
        /// </summary>
        [Test]
        public void PayReviewDateTest()
        {
            // TODO unit test for the property 'PayReviewDate'
        }
        /// <summary>
        /// Test the property 'Roles'
        /// </summary>
        [Test]
        public void RolesTest()
        {
            // TODO unit test for the property 'Roles'
        }
        /// <summary>
        /// Test the property 'Salaries'
        /// </summary>
        [Test]
        public void SalariesTest()
        {
            // TODO unit test for the property 'Salaries'
        }
        /// <summary>
        /// Test the property 'Allowances'
        /// </summary>
        [Test]
        public void AllowancesTest()
        {
            // TODO unit test for the property 'Allowances'
        }

    }

}
