/* 
 * assembly.education
 *
 * Developer API for assembly.education.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: help@assembly.education
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using assembly-client-dotnet.Api;
using assembly-client-dotnet.Model;
using assembly-client-dotnet.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace assembly-client-dotnet.Test
{
    /// <summary>
    ///  Class for testing TeachingGroupList
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TeachingGroupListTests
    {
        // TODO uncomment below to declare an instance variable for TeachingGroupList
        //private TeachingGroupList instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TeachingGroupList
            //instance = new TeachingGroupList();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TeachingGroupList
        /// </summary>
        [Test]
        public void TeachingGroupListInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TeachingGroupList
            //Assert.IsInstanceOfType<TeachingGroupList> (instance, "variable 'instance' is a TeachingGroupList");
        }


        /// <summary>
        /// Test the property 'Object'
        /// </summary>
        [Test]
        public void ObjectTest()
        {
            // TODO unit test for the property 'Object'
        }
        /// <summary>
        /// Test the property 'TotalCount'
        /// </summary>
        [Test]
        public void TotalCountTest()
        {
            // TODO unit test for the property 'TotalCount'
        }
        /// <summary>
        /// Test the property 'TotalPages'
        /// </summary>
        [Test]
        public void TotalPagesTest()
        {
            // TODO unit test for the property 'TotalPages'
        }
        /// <summary>
        /// Test the property 'CurrentPage'
        /// </summary>
        [Test]
        public void CurrentPageTest()
        {
            // TODO unit test for the property 'CurrentPage'
        }
        /// <summary>
        /// Test the property 'PrevPage'
        /// </summary>
        [Test]
        public void PrevPageTest()
        {
            // TODO unit test for the property 'PrevPage'
        }
        /// <summary>
        /// Test the property 'NextPage'
        /// </summary>
        [Test]
        public void NextPageTest()
        {
            // TODO unit test for the property 'NextPage'
        }
        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Test]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }

    }

}
