/* 
 * assembly.education
 *
 * Developer API for assembly.education.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: help@assembly.education
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using AssemblyClient.Client;
using AssemblyClient.Api;
using AssemblyClient.Model;

namespace AssemblyClient.Test
{
    /// <summary>
    ///  Class for testing SchoolDetailsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class SchoolDetailsApiTests
    {
        private SchoolDetailsApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new SchoolDetailsApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SchoolDetailsApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' SchoolDetailsApi
            //Assert.IsInstanceOfType(typeof(SchoolDetailsApi), instance, "instance is a SchoolDetailsApi");
        }

        
        /// <summary>
        /// Test SchoolDetails
        /// </summary>
        [Test]
        public void SchoolDetailsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.SchoolDetails();
            //Assert.IsInstanceOf<SchoolDetails> (response, "response is SchoolDetails");
        }
        
    }

}
