/* 
 * Assembly Developer API
 *
 * The Assembly API is built around the REST and a collection of open standards/protocols in order to comply with as many consumers as possible.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: help@assembly.education
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using AssemblyClient.Client;
using AssemblyClient.Api;
using AssemblyClient.Model;

namespace AssemblyClient.Test
{
    /// <summary>
    ///  Class for testing StaffContractsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class StaffContractsApiTests
    {
        private StaffContractsApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new StaffContractsApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of StaffContractsApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' StaffContractsApi
            //Assert.IsInstanceOfType(typeof(StaffContractsApi), instance, "instance is a StaffContractsApi");
        }

        
        /// <summary>
        /// Test StaffContracts
        /// </summary>
        [Test]
        public void StaffContractsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? staffMemberId = null;
            //bool? date = null;
            //bool? roles = null;
            //bool? salaries = null;
            //bool? allowances = null;
            //DateTime? ifModifiedSince = null;
            //int? perPage = null;
            //int? page = null;
            //var response = instance.StaffContracts(staffMemberId, date, roles, salaries, allowances, ifModifiedSince, perPage, page);
            //Assert.IsInstanceOf<StaffMemberList> (response, "response is StaffMemberList");
        }
        
    }

}
