/* 
 * Assembly Developer API
 *
 * The Assembly API is built around the REST and a collection of open standards/protocols in order to comply with as many consumers as possible.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: help@assembly.education
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using AssemblyClient.Client;
using AssemblyClient.Api;
using AssemblyClient.Model;

namespace AssemblyClient.Test
{
    /// <summary>
    ///  Class for testing StaffMembersApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class StaffMembersApiTests
    {
        private StaffMembersApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new StaffMembersApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of StaffMembersApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' StaffMembersApi
            //Assert.IsInstanceOfType(typeof(StaffMembersApi), instance, "instance is a StaffMembersApi");
        }

        
        /// <summary>
        /// Test StaffMember
        /// </summary>
        [Test]
        public void StaffMemberTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? id = null;
            //bool? demographics = null;
            //bool? qualifications = null;
            //var response = instance.StaffMember(id, demographics, qualifications);
            //Assert.IsInstanceOf<StaffMember> (response, "response is StaffMember");
        }
        
        /// <summary>
        /// Test StaffMembers
        /// </summary>
        [Test]
        public void StaffMembersTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //bool? teachersOnly = null;
            //bool? demographics = null;
            //bool? qualifications = null;
            //DateTime? ifModifiedSince = null;
            //int? perPage = null;
            //int? page = null;
            //var response = instance.StaffMembers(teachersOnly, demographics, qualifications, ifModifiedSince, perPage, page);
            //Assert.IsInstanceOf<StaffMemberList> (response, "response is StaffMemberList");
        }
        
    }

}
