/* 
 * assembly.education
 *
 * Developer API for assembly.education.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: help@assembly.education
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AssemblyClient.Api;
using AssemblyClient.Model;
using AssemblyClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace AssemblyClient.Test
{
    /// <summary>
    ///  Class for testing AcademicYearListData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AcademicYearListDataTests
    {
        // TODO uncomment below to declare an instance variable for AcademicYearListData
        //private AcademicYearListData instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AcademicYearListData
            //instance = new AcademicYearListData();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AcademicYearListData
        /// </summary>
        [Test]
        public void AcademicYearListDataInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AcademicYearListData
            //Assert.IsInstanceOfType<AcademicYearListData> (instance, "variable 'instance' is a AcademicYearListData");
        }


        /// <summary>
        /// Test the property 'id'
        /// </summary>
        [Test]
        public void idTest()
        {
            // TODO unit test for the property 'id'
        }
        /// <summary>
        /// Test the property 'name'
        /// </summary>
        [Test]
        public void nameTest()
        {
            // TODO unit test for the property 'name'
        }
        /// <summary>
        /// Test the property 'start_date'
        /// </summary>
        [Test]
        public void start_dateTest()
        {
            // TODO unit test for the property 'start_date'
        }
        /// <summary>
        /// Test the property 'end_date'
        /// </summary>
        [Test]
        public void end_dateTest()
        {
            // TODO unit test for the property 'end_date'
        }
        /// <summary>
        /// Test the property 'terms'
        /// </summary>
        [Test]
        public void termsTest()
        {
            // TODO unit test for the property 'terms'
        }

    }

}
