/* 
 * assembly.education
 *
 * Developer API for assembly.education.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: help@assembly.education
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AssemblyClient.Api;
using AssemblyClient.Model;
using AssemblyClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace AssemblyClient.Test
{
    /// <summary>
    ///  Class for testing AssessmentListData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AssessmentListDataTests
    {
        // TODO uncomment below to declare an instance variable for AssessmentListData
        //private AssessmentListData instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AssessmentListData
            //instance = new AssessmentListData();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AssessmentListData
        /// </summary>
        [Test]
        public void AssessmentListDataInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AssessmentListData
            //Assert.IsInstanceOfType<AssessmentListData> (instance, "variable 'instance' is a AssessmentListData");
        }


        /// <summary>
        /// Test the property '_object'
        /// </summary>
        [Test]
        public void _objectTest()
        {
            // TODO unit test for the property '_object'
        }
        /// <summary>
        /// Test the property 'id'
        /// </summary>
        [Test]
        public void idTest()
        {
            // TODO unit test for the property 'id'
        }
        /// <summary>
        /// Test the property 'name'
        /// </summary>
        [Test]
        public void nameTest()
        {
            // TODO unit test for the property 'name'
        }
        /// <summary>
        /// Test the property 'family_id'
        /// </summary>
        [Test]
        public void family_idTest()
        {
            // TODO unit test for the property 'family_id'
        }
        /// <summary>
        /// Test the property 'family_name'
        /// </summary>
        [Test]
        public void family_nameTest()
        {
            // TODO unit test for the property 'family_name'
        }
        /// <summary>
        /// Test the property 'mis_mappings'
        /// </summary>
        [Test]
        public void mis_mappingsTest()
        {
            // TODO unit test for the property 'mis_mappings'
        }

    }

}
