/* 
 * assembly.education
 *
 * Developer API for assembly.education.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: help@assembly.education
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AssemblyClient.Api;
using AssemblyClient.Model;
using AssemblyClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace AssemblyClient.Test
{
    /// <summary>
    ///  Class for testing ContactRelationship
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ContactRelationshipTests
    {
        // TODO uncomment below to declare an instance variable for ContactRelationship
        //private ContactRelationship instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ContactRelationship
            //instance = new ContactRelationship();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ContactRelationship
        /// </summary>
        [Test]
        public void ContactRelationshipInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ContactRelationship
            //Assert.IsInstanceOfType<ContactRelationship> (instance, "variable 'instance' is a ContactRelationship");
        }


        /// <summary>
        /// Test the property '_object'
        /// </summary>
        [Test]
        public void _objectTest()
        {
            // TODO unit test for the property '_object'
        }
        /// <summary>
        /// Test the property 'relationship_type'
        /// </summary>
        [Test]
        public void relationship_typeTest()
        {
            // TODO unit test for the property 'relationship_type'
        }
        /// <summary>
        /// Test the property 'priority'
        /// </summary>
        [Test]
        public void priorityTest()
        {
            // TODO unit test for the property 'priority'
        }
        /// <summary>
        /// Test the property 'parental_responsibility'
        /// </summary>
        [Test]
        public void parental_responsibilityTest()
        {
            // TODO unit test for the property 'parental_responsibility'
        }

    }

}
