/* 
 * assembly.education
 *
 * Developer API for assembly.education.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: help@assembly.education
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AssemblyClient.Api;
using AssemblyClient.Model;
using AssemblyClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace AssemblyClient.Test
{
    /// <summary>
    ///  Class for testing ContactStudents
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ContactStudentsTests
    {
        // TODO uncomment below to declare an instance variable for ContactStudents
        //private ContactStudents instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ContactStudents
            //instance = new ContactStudents();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ContactStudents
        /// </summary>
        [Test]
        public void ContactStudentsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ContactStudents
            //Assert.IsInstanceOfType<ContactStudents> (instance, "variable 'instance' is a ContactStudents");
        }


        /// <summary>
        /// Test the property '_object'
        /// </summary>
        [Test]
        public void _objectTest()
        {
            // TODO unit test for the property '_object'
        }
        /// <summary>
        /// Test the property 'student_id'
        /// </summary>
        [Test]
        public void student_idTest()
        {
            // TODO unit test for the property 'student_id'
        }
        /// <summary>
        /// Test the property 'relationship'
        /// </summary>
        [Test]
        public void relationshipTest()
        {
            // TODO unit test for the property 'relationship'
        }

    }

}
