/* 
 * assembly.education
 *
 * Developer API for assembly.education.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: help@assembly.education
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AssemblyClient.Api;
using AssemblyClient.Model;
using AssemblyClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace AssemblyClient.Test
{
    /// <summary>
    ///  Class for testing ContactEmails
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ContactEmailsTests
    {
        // TODO uncomment below to declare an instance variable for ContactEmails
        //private ContactEmails instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ContactEmails
            //instance = new ContactEmails();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ContactEmails
        /// </summary>
        [Test]
        public void ContactEmailsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ContactEmails
            //Assert.IsInstanceOfType<ContactEmails> (instance, "variable 'instance' is a ContactEmails");
        }


        /// <summary>
        /// Test the property '_object'
        /// </summary>
        [Test]
        public void _objectTest()
        {
            // TODO unit test for the property '_object'
        }
        /// <summary>
        /// Test the property 'id'
        /// </summary>
        [Test]
        public void idTest()
        {
            // TODO unit test for the property 'id'
        }
        /// <summary>
        /// Test the property 'email'
        /// </summary>
        [Test]
        public void emailTest()
        {
            // TODO unit test for the property 'email'
        }
        /// <summary>
        /// Test the property 'type'
        /// </summary>
        [Test]
        public void typeTest()
        {
            // TODO unit test for the property 'type'
        }
        /// <summary>
        /// Test the property 'is_primary'
        /// </summary>
        [Test]
        public void is_primaryTest()
        {
            // TODO unit test for the property 'is_primary'
        }

    }

}
