/* 
 * assembly.education
 *
 * Developer API for assembly.education.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: help@assembly.education
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AssemblyClient.Api;
using AssemblyClient.Model;
using AssemblyClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace AssemblyClient.Test
{
    /// <summary>
    ///  Class for testing CreateResultPayloadListData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CreateResultPayloadListDataTests
    {
        // TODO uncomment below to declare an instance variable for CreateResultPayloadListData
        //private CreateResultPayloadListData instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CreateResultPayloadListData
            //instance = new CreateResultPayloadListData();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CreateResultPayloadListData
        /// </summary>
        [Test]
        public void CreateResultPayloadListDataInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CreateResultPayloadListData
            //Assert.IsInstanceOfType<CreateResultPayloadListData> (instance, "variable 'instance' is a CreateResultPayloadListData");
        }


        /// <summary>
        /// Test the property 'subject_id'
        /// </summary>
        [Test]
        public void subject_idTest()
        {
            // TODO unit test for the property 'subject_id'
        }
        /// <summary>
        /// Test the property 'facet_id'
        /// </summary>
        [Test]
        public void facet_idTest()
        {
            // TODO unit test for the property 'facet_id'
        }
        /// <summary>
        /// Test the property 'assessment_point_rank'
        /// </summary>
        [Test]
        public void assessment_point_rankTest()
        {
            // TODO unit test for the property 'assessment_point_rank'
        }
        /// <summary>
        /// Test the property 'assessment_id'
        /// </summary>
        [Test]
        public void assessment_idTest()
        {
            // TODO unit test for the property 'assessment_id'
        }
        /// <summary>
        /// Test the property 'results'
        /// </summary>
        [Test]
        public void resultsTest()
        {
            // TODO unit test for the property 'results'
        }

    }

}
