/* 
 * Assembly Developer API
 *
 * The Assembly API is built around the REST and a collection of open standards/protocols in order to comply with as many consumers as possible.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: help@assembly.education
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AssemblyClient.Api;
using AssemblyClient.Model;
using AssemblyClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace AssemblyClient.Test
{
    /// <summary>
    ///  Class for testing Facet
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class FacetTests
    {
        // TODO uncomment below to declare an instance variable for Facet
        //private Facet instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Facet
            //instance = new Facet();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Facet
        /// </summary>
        [Test]
        public void FacetInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Facet
            //Assert.IsInstanceOfType<Facet> (instance, "variable 'instance' is a Facet");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

    }

}
