/* 
 * assembly.education
 *
 * Developer API for assembly.education.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: help@assembly.education
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AssemblyClient.Api;
using AssemblyClient.Model;
using AssemblyClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace AssemblyClient.Test
{
    /// <summary>
    ///  Class for testing GradesetListData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class GradesetListDataTests
    {
        // TODO uncomment below to declare an instance variable for GradesetListData
        //private GradesetListData instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GradesetListData
            //instance = new GradesetListData();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GradesetListData
        /// </summary>
        [Test]
        public void GradesetListDataInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GradesetListData
            //Assert.IsInstanceOfType<GradesetListData> (instance, "variable 'instance' is a GradesetListData");
        }


        /// <summary>
        /// Test the property '_object'
        /// </summary>
        [Test]
        public void _objectTest()
        {
            // TODO unit test for the property '_object'
        }
        /// <summary>
        /// Test the property 'id'
        /// </summary>
        [Test]
        public void idTest()
        {
            // TODO unit test for the property 'id'
        }
        /// <summary>
        /// Test the property 'name'
        /// </summary>
        [Test]
        public void nameTest()
        {
            // TODO unit test for the property 'name'
        }
        /// <summary>
        /// Test the property 'grades'
        /// </summary>
        [Test]
        public void gradesTest()
        {
            // TODO unit test for the property 'grades'
        }

    }

}
