/* 
 * assembly.education
 *
 * Developer API for assembly.education.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: help@assembly.education
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AssemblyClient.Api;
using AssemblyClient.Model;
using AssemblyClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace AssemblyClient.Test
{
    /// <summary>
    ///  Class for testing Result
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ResultTests
    {
        // TODO uncomment below to declare an instance variable for Result
        //private Result instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Result
            //instance = new Result();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Result
        /// </summary>
        [Test]
        public void ResultInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Result
            //Assert.IsInstanceOfType<Result> (instance, "variable 'instance' is a Result");
        }


        /// <summary>
        /// Test the property '_object'
        /// </summary>
        [Test]
        public void _objectTest()
        {
            // TODO unit test for the property '_object'
        }
        /// <summary>
        /// Test the property 'id'
        /// </summary>
        [Test]
        public void idTest()
        {
            // TODO unit test for the property 'id'
        }
        /// <summary>
        /// Test the property 'student_id'
        /// </summary>
        [Test]
        public void student_idTest()
        {
            // TODO unit test for the property 'student_id'
        }
        /// <summary>
        /// Test the property 'subject_id'
        /// </summary>
        [Test]
        public void subject_idTest()
        {
            // TODO unit test for the property 'subject_id'
        }
        /// <summary>
        /// Test the property 'assessment_id'
        /// </summary>
        [Test]
        public void assessment_idTest()
        {
            // TODO unit test for the property 'assessment_id'
        }
        /// <summary>
        /// Test the property 'assessment_point_rank'
        /// </summary>
        [Test]
        public void assessment_point_rankTest()
        {
            // TODO unit test for the property 'assessment_point_rank'
        }
        /// <summary>
        /// Test the property 'aspect_id'
        /// </summary>
        [Test]
        public void aspect_idTest()
        {
            // TODO unit test for the property 'aspect_id'
        }
        /// <summary>
        /// Test the property 'grade_id'
        /// </summary>
        [Test]
        public void grade_idTest()
        {
            // TODO unit test for the property 'grade_id'
        }
        /// <summary>
        /// Test the property 'result_date'
        /// </summary>
        [Test]
        public void result_dateTest()
        {
            // TODO unit test for the property 'result_date'
        }
        /// <summary>
        /// Test the property 'created_at'
        /// </summary>
        [Test]
        public void created_atTest()
        {
            // TODO unit test for the property 'created_at'
        }
        /// <summary>
        /// Test the property 'updated_at'
        /// </summary>
        [Test]
        public void updated_atTest()
        {
            // TODO unit test for the property 'updated_at'
        }

    }

}
