/* 
 * assembly.education
 *
 * Developer API for assembly.education.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: help@assembly.education
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AssemblyClient.Api;
using AssemblyClient.Model;
using AssemblyClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace AssemblyClient.Test
{
    /// <summary>
    ///  Class for testing SchoolDetails
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SchoolDetailsTests
    {
        // TODO uncomment below to declare an instance variable for SchoolDetails
        //private SchoolDetails instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SchoolDetails
            //instance = new SchoolDetails();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SchoolDetails
        /// </summary>
        [Test]
        public void SchoolDetailsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SchoolDetails
            //Assert.IsInstanceOfType<SchoolDetails> (instance, "variable 'instance' is a SchoolDetails");
        }


        /// <summary>
        /// Test the property '_object'
        /// </summary>
        [Test]
        public void _objectTest()
        {
            // TODO unit test for the property '_object'
        }
        /// <summary>
        /// Test the property 'id'
        /// </summary>
        [Test]
        public void idTest()
        {
            // TODO unit test for the property 'id'
        }
        /// <summary>
        /// Test the property 'name'
        /// </summary>
        [Test]
        public void nameTest()
        {
            // TODO unit test for the property 'name'
        }
        /// <summary>
        /// Test the property 'urn'
        /// </summary>
        [Test]
        public void urnTest()
        {
            // TODO unit test for the property 'urn'
        }
        /// <summary>
        /// Test the property 'la_code'
        /// </summary>
        [Test]
        public void la_codeTest()
        {
            // TODO unit test for the property 'la_code'
        }
        /// <summary>
        /// Test the property 'la_name'
        /// </summary>
        [Test]
        public void la_nameTest()
        {
            // TODO unit test for the property 'la_name'
        }
        /// <summary>
        /// Test the property 'establishment_number'
        /// </summary>
        [Test]
        public void establishment_numberTest()
        {
            // TODO unit test for the property 'establishment_number'
        }
        /// <summary>
        /// Test the property 'establishment_type'
        /// </summary>
        [Test]
        public void establishment_typeTest()
        {
            // TODO unit test for the property 'establishment_type'
        }
        /// <summary>
        /// Test the property 'phase'
        /// </summary>
        [Test]
        public void phaseTest()
        {
            // TODO unit test for the property 'phase'
        }
        /// <summary>
        /// Test the property 'street'
        /// </summary>
        [Test]
        public void streetTest()
        {
            // TODO unit test for the property 'street'
        }
        /// <summary>
        /// Test the property 'town'
        /// </summary>
        [Test]
        public void townTest()
        {
            // TODO unit test for the property 'town'
        }
        /// <summary>
        /// Test the property 'postcode'
        /// </summary>
        [Test]
        public void postcodeTest()
        {
            // TODO unit test for the property 'postcode'
        }
        /// <summary>
        /// Test the property 'head_teacher'
        /// </summary>
        [Test]
        public void head_teacherTest()
        {
            // TODO unit test for the property 'head_teacher'
        }

    }

}
