/* 
 * assembly.education
 *
 * Developer API for assembly.education.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: help@assembly.education
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AssemblyClient.Api;
using AssemblyClient.Model;
using AssemblyClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace AssemblyClient.Test
{
    /// <summary>
    ///  Class for testing StaffContractSalaries
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class StaffContractSalariesTests
    {
        // TODO uncomment below to declare an instance variable for StaffContractSalaries
        //private StaffContractSalaries instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of StaffContractSalaries
            //instance = new StaffContractSalaries();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of StaffContractSalaries
        /// </summary>
        [Test]
        public void StaffContractSalariesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" StaffContractSalaries
            //Assert.IsInstanceOfType<StaffContractSalaries> (instance, "variable 'instance' is a StaffContractSalaries");
        }


        /// <summary>
        /// Test the property 'Object'
        /// </summary>
        [Test]
        public void ObjectTest()
        {
            // TODO unit test for the property 'Object'
        }
        /// <summary>
        /// Test the property 'HoursPerWeek'
        /// </summary>
        [Test]
        public void HoursPerWeekTest()
        {
            // TODO unit test for the property 'HoursPerWeek'
        }
        /// <summary>
        /// Test the property 'Fte'
        /// </summary>
        [Test]
        public void FteTest()
        {
            // TODO unit test for the property 'Fte'
        }
        /// <summary>
        /// Test the property 'WeeksPerYear'
        /// </summary>
        [Test]
        public void WeeksPerYearTest()
        {
            // TODO unit test for the property 'WeeksPerYear'
        }
        /// <summary>
        /// Test the property 'PayRange'
        /// </summary>
        [Test]
        public void PayRangeTest()
        {
            // TODO unit test for the property 'PayRange'
        }
        /// <summary>
        /// Test the property 'StartDate'
        /// </summary>
        [Test]
        public void StartDateTest()
        {
            // TODO unit test for the property 'StartDate'
        }
        /// <summary>
        /// Test the property 'EndDate'
        /// </summary>
        [Test]
        public void EndDateTest()
        {
            // TODO unit test for the property 'EndDate'
        }
        /// <summary>
        /// Test the property 'PayScaleFramework'
        /// </summary>
        [Test]
        public void PayScaleFrameworkTest()
        {
            // TODO unit test for the property 'PayScaleFramework'
        }
        /// <summary>
        /// Test the property 'RegionalSpine'
        /// </summary>
        [Test]
        public void RegionalSpineTest()
        {
            // TODO unit test for the property 'RegionalSpine'
        }
        /// <summary>
        /// Test the property 'BasePay'
        /// </summary>
        [Test]
        public void BasePayTest()
        {
            // TODO unit test for the property 'BasePay'
        }
        /// <summary>
        /// Test the property 'ActualPay'
        /// </summary>
        [Test]
        public void ActualPayTest()
        {
            // TODO unit test for the property 'ActualPay'
        }
        /// <summary>
        /// Test the property 'SafeguardedSalary'
        /// </summary>
        [Test]
        public void SafeguardedSalaryTest()
        {
            // TODO unit test for the property 'SafeguardedSalary'
        }

    }

}
