/* 
 * Assembly Developer API
 *
 * The Assembly API is built around the REST and a collection of open standards/protocols in order to comply with as many consumers as possible.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: help@assembly.education
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AssemblyClient.Api;
using AssemblyClient.Model;
using AssemblyClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace AssemblyClient.Test
{
    /// <summary>
    ///  Class for testing StaffAbsence
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class StaffAbsenceTests
    {
        // TODO uncomment below to declare an instance variable for StaffAbsence
        //private StaffAbsence instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of StaffAbsence
            //instance = new StaffAbsence();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of StaffAbsence
        /// </summary>
        [Test]
        public void StaffAbsenceInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" StaffAbsence
            //Assert.IsInstanceOfType<StaffAbsence> (instance, "variable 'instance' is a StaffAbsence");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'StaffMemberId'
        /// </summary>
        [Test]
        public void StaffMemberIdTest()
        {
            // TODO unit test for the property 'StaffMemberId'
        }
        /// <summary>
        /// Test the property 'StartDate'
        /// </summary>
        [Test]
        public void StartDateTest()
        {
            // TODO unit test for the property 'StartDate'
        }
        /// <summary>
        /// Test the property 'EndDate'
        /// </summary>
        [Test]
        public void EndDateTest()
        {
            // TODO unit test for the property 'EndDate'
        }
        /// <summary>
        /// Test the property 'WorkingDaysLost'
        /// </summary>
        [Test]
        public void WorkingDaysLostTest()
        {
            // TODO unit test for the property 'WorkingDaysLost'
        }
        /// <summary>
        /// Test the property 'AbsenceCategory'
        /// </summary>
        [Test]
        public void AbsenceCategoryTest()
        {
            // TODO unit test for the property 'AbsenceCategory'
        }
        /// <summary>
        /// Test the property 'IllnessCategory'
        /// </summary>
        [Test]
        public void IllnessCategoryTest()
        {
            // TODO unit test for the property 'IllnessCategory'
        }
        /// <summary>
        /// Test the property 'PayRate'
        /// </summary>
        [Test]
        public void PayRateTest()
        {
            // TODO unit test for the property 'PayRate'
        }

    }

}
