/* 
 * assembly.education
 *
 * Developer API for assembly.education.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: help@assembly.education
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AssemblyClient.Api;
using AssemblyClient.Model;
using AssemblyClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace AssemblyClient.Test
{
    /// <summary>
    ///  Class for testing StaffMember
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class StaffMemberTests
    {
        // TODO uncomment below to declare an instance variable for StaffMember
        //private StaffMember instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of StaffMember
            //instance = new StaffMember();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of StaffMember
        /// </summary>
        [Test]
        public void StaffMemberInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" StaffMember
            //Assert.IsInstanceOfType<StaffMember> (instance, "variable 'instance' is a StaffMember");
        }


        /// <summary>
        /// Test the property '_object'
        /// </summary>
        [Test]
        public void _objectTest()
        {
            // TODO unit test for the property '_object'
        }
        /// <summary>
        /// Test the property 'id'
        /// </summary>
        [Test]
        public void idTest()
        {
            // TODO unit test for the property 'id'
        }
        /// <summary>
        /// Test the property 'mis_id'
        /// </summary>
        [Test]
        public void mis_idTest()
        {
            // TODO unit test for the property 'mis_id'
        }
        /// <summary>
        /// Test the property 'staff_code'
        /// </summary>
        [Test]
        public void staff_codeTest()
        {
            // TODO unit test for the property 'staff_code'
        }
        /// <summary>
        /// Test the property 'first_name'
        /// </summary>
        [Test]
        public void first_nameTest()
        {
            // TODO unit test for the property 'first_name'
        }
        /// <summary>
        /// Test the property 'legal_first_name'
        /// </summary>
        [Test]
        public void legal_first_nameTest()
        {
            // TODO unit test for the property 'legal_first_name'
        }
        /// <summary>
        /// Test the property 'middle_name'
        /// </summary>
        [Test]
        public void middle_nameTest()
        {
            // TODO unit test for the property 'middle_name'
        }
        /// <summary>
        /// Test the property 'last_name'
        /// </summary>
        [Test]
        public void last_nameTest()
        {
            // TODO unit test for the property 'last_name'
        }
        /// <summary>
        /// Test the property 'legal_last_name'
        /// </summary>
        [Test]
        public void legal_last_nameTest()
        {
            // TODO unit test for the property 'legal_last_name'
        }
        /// <summary>
        /// Test the property 'former_last_name'
        /// </summary>
        [Test]
        public void former_last_nameTest()
        {
            // TODO unit test for the property 'former_last_name'
        }
        /// <summary>
        /// Test the property 'dob'
        /// </summary>
        [Test]
        public void dobTest()
        {
            // TODO unit test for the property 'dob'
        }
        /// <summary>
        /// Test the property 'title'
        /// </summary>
        [Test]
        public void titleTest()
        {
            // TODO unit test for the property 'title'
        }
        /// <summary>
        /// Test the property 'email'
        /// </summary>
        [Test]
        public void emailTest()
        {
            // TODO unit test for the property 'email'
        }
        /// <summary>
        /// Test the property 'is_teaching_staff'
        /// </summary>
        [Test]
        public void is_teaching_staffTest()
        {
            // TODO unit test for the property 'is_teaching_staff'
        }
        /// <summary>
        /// Test the property 'included_in_census'
        /// </summary>
        [Test]
        public void included_in_censusTest()
        {
            // TODO unit test for the property 'included_in_census'
        }
        /// <summary>
        /// Test the property 'start_date'
        /// </summary>
        [Test]
        public void start_dateTest()
        {
            // TODO unit test for the property 'start_date'
        }
        /// <summary>
        /// Test the property 'end_date'
        /// </summary>
        [Test]
        public void end_dateTest()
        {
            // TODO unit test for the property 'end_date'
        }
        /// <summary>
        /// Test the property 'demographics'
        /// </summary>
        [Test]
        public void demographicsTest()
        {
            // TODO unit test for the property 'demographics'
        }
        /// <summary>
        /// Test the property 'qualification_info'
        /// </summary>
        [Test]
        public void qualification_infoTest()
        {
            // TODO unit test for the property 'qualification_info'
        }

    }

}
