/* 
 * assembly.education
 *
 * Developer API for assembly.education.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: help@assembly.education
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AssemblyClient.Api;
using AssemblyClient.Model;
using AssemblyClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace AssemblyClient.Test
{
    /// <summary>
    ///  Class for testing StudentDemographicsSenNeeds
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class StudentDemographicsSenNeedsTests
    {
        // TODO uncomment below to declare an instance variable for StudentDemographicsSenNeeds
        //private StudentDemographicsSenNeeds instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of StudentDemographicsSenNeeds
            //instance = new StudentDemographicsSenNeeds();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of StudentDemographicsSenNeeds
        /// </summary>
        [Test]
        public void StudentDemographicsSenNeedsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" StudentDemographicsSenNeeds
            //Assert.IsInstanceOfType<StudentDemographicsSenNeeds> (instance, "variable 'instance' is a StudentDemographicsSenNeeds");
        }


        /// <summary>
        /// Test the property 'Object'
        /// </summary>
        [Test]
        public void ObjectTest()
        {
            // TODO unit test for the property 'Object'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'StartDate'
        /// </summary>
        [Test]
        public void StartDateTest()
        {
            // TODO unit test for the property 'StartDate'
        }
        /// <summary>
        /// Test the property 'SenNeedCode'
        /// </summary>
        [Test]
        public void SenNeedCodeTest()
        {
            // TODO unit test for the property 'SenNeedCode'
        }
        /// <summary>
        /// Test the property 'SenNeedName'
        /// </summary>
        [Test]
        public void SenNeedNameTest()
        {
            // TODO unit test for the property 'SenNeedName'
        }
        /// <summary>
        /// Test the property 'SenBroadNeedTypeCode'
        /// </summary>
        [Test]
        public void SenBroadNeedTypeCodeTest()
        {
            // TODO unit test for the property 'SenBroadNeedTypeCode'
        }
        /// <summary>
        /// Test the property 'SenBroadNeedTypeName'
        /// </summary>
        [Test]
        public void SenBroadNeedTypeNameTest()
        {
            // TODO unit test for the property 'SenBroadNeedTypeName'
        }
        /// <summary>
        /// Test the property 'Priority'
        /// </summary>
        [Test]
        public void PriorityTest()
        {
            // TODO unit test for the property 'Priority'
        }

    }

}
