/* 
 * assembly.education
 *
 * Developer API for assembly.education.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: help@assembly.education
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AssemblyClient.Api;
using AssemblyClient.Model;
using AssemblyClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace AssemblyClient.Test
{
    /// <summary>
    ///  Class for testing TeachingGroupListData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TeachingGroupListDataTests
    {
        // TODO uncomment below to declare an instance variable for TeachingGroupListData
        //private TeachingGroupListData instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TeachingGroupListData
            //instance = new TeachingGroupListData();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TeachingGroupListData
        /// </summary>
        [Test]
        public void TeachingGroupListDataInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TeachingGroupListData
            //Assert.IsInstanceOfType<TeachingGroupListData> (instance, "variable 'instance' is a TeachingGroupListData");
        }


        /// <summary>
        /// Test the property 'Object'
        /// </summary>
        [Test]
        public void ObjectTest()
        {
            // TODO unit test for the property 'Object'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'StartDate'
        /// </summary>
        [Test]
        public void StartDateTest()
        {
            // TODO unit test for the property 'StartDate'
        }
        /// <summary>
        /// Test the property 'EndDate'
        /// </summary>
        [Test]
        public void EndDateTest()
        {
            // TODO unit test for the property 'EndDate'
        }
        /// <summary>
        /// Test the property 'SupervisorIds'
        /// </summary>
        [Test]
        public void SupervisorIdsTest()
        {
            // TODO unit test for the property 'SupervisorIds'
        }
        /// <summary>
        /// Test the property 'StudentIds'
        /// </summary>
        [Test]
        public void StudentIdsTest()
        {
            // TODO unit test for the property 'StudentIds'
        }
        /// <summary>
        /// Test the property 'Subject'
        /// </summary>
        [Test]
        public void SubjectTest()
        {
            // TODO unit test for the property 'Subject'
        }
        /// <summary>
        /// Test the property 'MisLevel'
        /// </summary>
        [Test]
        public void MisLevelTest()
        {
            // TODO unit test for the property 'MisLevel'
        }

    }

}
